version: '2'
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        restart: always
        ports:
          - "5000:5000"
        depends_on:
          - redis
        volumes:
          - .:/app

    redis:
        image: redis:latest
        container_name: redis
        ports:
         - '6379:6379'


    worker:
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - .:/app
        entrypoint: celery
        command: -A app.celery_tasks.celery worker --loglevel=info
        links:
            - redis
        depends_on:
            - redis